// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57wS1634OsgjNpWYJ4upwdJE4TfDWxuo',
    appId: '1:723631091689:web:9f8625b76b34ccff076578',
    messagingSenderId: '723631091689',
    projectId: 'reddit-clone-a8c27',
    authDomain: 'reddit-clone-a8c27.firebaseapp.com',
    storageBucket: 'reddit-clone-a8c27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQt9y0fAG_1nA6zTwGQKXpnD4zJ-Z7uzo',
    appId: '1:723631091689:android:773840b7307e5554076578',
    messagingSenderId: '723631091689',
    projectId: 'reddit-clone-a8c27',
    storageBucket: 'reddit-clone-a8c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tpoGRIl-Z2oLQyYJT9JgtdT972-PV0Q',
    appId: '1:723631091689:ios:48edff71c3551c7b076578',
    messagingSenderId: '723631091689',
    projectId: 'reddit-clone-a8c27',
    storageBucket: 'reddit-clone-a8c27.firebasestorage.app',
    androidClientId: '723631091689-70ucubju3hg49671o8ru730u6npvsr6e.apps.googleusercontent.com',
    iosClientId: '723631091689-eita7vc198i2pbs06osuile1nbb9p6nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRedditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tpoGRIl-Z2oLQyYJT9JgtdT972-PV0Q',
    appId: '1:723631091689:ios:48edff71c3551c7b076578',
    messagingSenderId: '723631091689',
    projectId: 'reddit-clone-a8c27',
    storageBucket: 'reddit-clone-a8c27.firebasestorage.app',
    androidClientId: '723631091689-70ucubju3hg49671o8ru730u6npvsr6e.apps.googleusercontent.com',
    iosClientId: '723631091689-eita7vc198i2pbs06osuile1nbb9p6nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRedditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB57wS1634OsgjNpWYJ4upwdJE4TfDWxuo',
    appId: '1:723631091689:web:98ff611458b9ebe9076578',
    messagingSenderId: '723631091689',
    projectId: 'reddit-clone-a8c27',
    authDomain: 'reddit-clone-a8c27.firebaseapp.com',
    storageBucket: 'reddit-clone-a8c27.firebasestorage.app',
  );
}
